name: Lint TS
on: [push, pull_request]
jobs:
  lint-ts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./WebUI
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint:ci
      - run: npm run format:ci
